// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/business-instagram": {
            "get": {
                "description": "Business Instagram一覧を取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "business-instagram"
                ],
                "summary": "Business Instagram一覧取得",
                "responses": {
                    "201": {
                        "description": "Business Instagram",
                        "schema": {
                            "$ref": "#/definitions/res.BusinessInstagramList"
                        }
                    },
                    "400": {
                        "description": "不正なリクエスト",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Business Instagramを作成します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "business-instagram"
                ],
                "summary": "Business Instagram作成",
                "parameters": [
                    {
                        "description": "作成データ",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.BusinessInstagram"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "作成されたBusiness Instagram",
                        "schema": {
                            "$ref": "#/definitions/res.BusinessInstagram"
                        }
                    },
                    "400": {
                        "description": "不正なリクエスト",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/business-instagram/{id}": {
            "get": {
                "description": "Business Instagramを取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "business-instagram"
                ],
                "summary": "Business Instagram取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "取得件数",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "オフセット",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Business Instagram Detail",
                        "schema": {
                            "$ref": "#/definitions/res.BusinessInstagramDetail"
                        }
                    },
                    "400": {
                        "description": "不正なリクエスト",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Business Instagramを更新します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "business-instagram"
                ],
                "summary": "Business Instagram更新",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Business Instagram ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新データ",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.BusinessInstagram"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新されたBusiness Instagram",
                        "schema": {
                            "$ref": "#/definitions/res.BusinessInstagram"
                        }
                    },
                    "400": {
                        "description": "不正なリクエスト",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "見つかりません",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Business Instagramを削除します",
                "tags": [
                    "business-instagram"
                ],
                "summary": "Business Instagram削除",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Business Instagram ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "400": {
                        "description": "不正なリクエスト",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "見つかりません",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/google-business": {
            "get": {
                "description": "Google Businessの一覧を取得します（ページング対応）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "google-business"
                ],
                "summary": "Google Business一覧取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "取得件数（デフォルト: 20）",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "オフセット（デフォルト: 0）",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Google Business一覧",
                        "schema": {
                            "$ref": "#/definitions/res.GoogleBusinessList"
                        }
                    },
                    "400": {
                        "description": "不正なリクエスト",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/google-business/fetch": {
            "post": {
                "description": "Google Businessを同期します",
                "tags": [
                    "google-business"
                ],
                "summary": "Google Businessの同期",
                "responses": {
                    "400": {
                        "description": "不正なリクエスト",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/sync/business-instagram": {
            "post": {
                "description": "全ての顧客のデータを同期します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sync"
                ],
                "summary": "instagram =\u003e wordpressにおける全顧客データ同期",
                "responses": {
                    "200": {
                        "description": "全顧客同期完了",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/sync/business-instagram/{id}": {
            "post": {
                "description": "全ての顧客のデータを同期します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sync"
                ],
                "summary": "instagram =\u003e wordpressにおける顧客データ同期",
                "responses": {
                    "200": {
                        "description": "全顧客同期完了",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/sync/wordpress-instagram": {
            "post": {
                "description": "全ての顧客のデータを同期します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sync"
                ],
                "summary": "instagram =\u003e wordpressにおける全顧客データ同期",
                "responses": {
                    "200": {
                        "description": "全顧客同期完了",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/sync/wordpress-instagram/{id}": {
            "post": {
                "description": "全ての顧客のデータを同期します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sync"
                ],
                "summary": "instagram =\u003e wordpressにおける顧客データ同期",
                "responses": {
                    "200": {
                        "description": "全顧客同期完了",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/token": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "token"
                ],
                "summary": "トークンを取得します。",
                "responses": {
                    "200": {
                        "description": "トークン情報",
                        "schema": {
                            "$ref": "#/definitions/res.Token"
                        }
                    },
                    "500": {
                        "description": "内部サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "token"
                ],
                "summary": "トークンを保存します。",
                "responses": {
                    "200": {
                        "description": "更新完了",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/token/check": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "token"
                ],
                "summary": "トークンの認証情報を取得する",
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/wordpress-instagram": {
            "get": {
                "description": "Wordpress Instagramの一覧を取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wordpress-instagram"
                ],
                "summary": "Wordpress Instagram一覧取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "取得件数",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "オフセット",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "名前",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "WordPress URL",
                        "name": "wordpress",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Instagram ID",
                        "name": "instagram_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "ステータス",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "削除ハッシュ",
                        "name": "delete_hash",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "顧客タイプ",
                        "name": "customer_type",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Wordpress Instagram一覧",
                        "schema": {
                            "$ref": "#/definitions/res.WordpressInstagramList"
                        }
                    },
                    "400": {
                        "description": "不正なリクエスト",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "post": {
                "description": "Wordpress Instagramを作成します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wordpress-instagram"
                ],
                "summary": "Wordpress Instagram作成",
                "parameters": [
                    {
                        "description": "作成データ",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.CreateWordpressInstagram"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "作成されたWordpress Instagram",
                        "schema": {
                            "$ref": "#/definitions/res.WordpressInstagram"
                        }
                    },
                    "400": {
                        "description": "不正なリクエスト",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/wordpress-instagram/count": {
            "get": {
                "description": "Wordpress Instagramの件数を取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wordpress-instagram"
                ],
                "summary": "Wordpress Instagramの件数を取得",
                "responses": {
                    "200": {
                        "description": "Wordpress Instagram一覧",
                        "schema": {
                            "$ref": "#/definitions/res.WordpressInstagramList"
                        }
                    },
                    "400": {
                        "description": "不正なリクエスト",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/wordpress-instagram/{id}": {
            "get": {
                "description": "Wordpress Instagramの詳細を取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wordpress-instagram"
                ],
                "summary": "Wordpress Instagram詳細取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Wordpress Instagram ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "投稿取得件数",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "投稿オフセット",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Wordpress Instagram詳細",
                        "schema": {
                            "$ref": "#/definitions/res.WordpressInstagramDetail"
                        }
                    },
                    "404": {
                        "description": "見つかりません",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "put": {
                "description": "Wordpress Instagramを更新します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wordpress-instagram"
                ],
                "summary": "Wordpress Instagram更新",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Wordpress Instagram ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新データ",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/req.UpdateWordpressInstagram"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新されたWordpress Instagram",
                        "schema": {
                            "$ref": "#/definitions/res.WordpressInstagram"
                        }
                    },
                    "400": {
                        "description": "不正なリクエスト",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "見つかりません",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            },
            "delete": {
                "description": "Wordpress Instagramを削除します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wordpress-instagram"
                ],
                "summary": "Wordpress Instagram削除",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Wordpress Instagram ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "削除成功",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "見つかりません",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "req.BusinessInstagram": {
            "type": "object",
            "properties": {
                "business_name": {
                    "type": "string"
                },
                "instagram_id": {
                    "type": "string"
                },
                "memo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        },
        "req.CreateWordpressInstagram": {
            "type": "object",
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "delete_hash": {
                    "type": "boolean"
                },
                "instagram_id": {
                    "type": "string"
                },
                "memo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "wordpress_domain": {
                    "type": "string"
                }
            }
        },
        "req.UpdateWordpressInstagram": {
            "type": "object",
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "delete_hash": {
                    "type": "boolean"
                },
                "instagram_id": {
                    "type": "string"
                },
                "memo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "wordpress_domain": {
                    "type": "string"
                }
            }
        },
        "res.BusinessInstagram": {
            "type": "object",
            "properties": {
                "business_name": {
                    "type": "string"
                },
                "business_title": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "instagram_id": {
                    "type": "string"
                },
                "instagram_name": {
                    "type": "string"
                },
                "maps_url": {
                    "type": "string"
                },
                "memo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "res.BusinessInstagramDetail": {
            "type": "object",
            "properties": {
                "business_name": {
                    "type": "string"
                },
                "business_title": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "google_posts": {
                    "$ref": "#/definitions/res.GooglePosts"
                },
                "id": {
                    "type": "integer"
                },
                "instagram_id": {
                    "type": "string"
                },
                "instagram_name": {
                    "type": "string"
                },
                "maps_url": {
                    "type": "string"
                },
                "memo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "res.BusinessInstagramList": {
            "type": "object",
            "properties": {
                "business_instagram_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/res.BusinessInstagram"
                    }
                },
                "count": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "res.GoogleBusiness": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "res.GoogleBusinessList": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "google_business_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/res.GoogleBusiness"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "res.GooglePost": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "google_url": {
                    "type": "string"
                },
                "instagram_url": {
                    "type": "string"
                },
                "post_type": {
                    "type": "string"
                }
            }
        },
        "res.GooglePosts": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "google_posts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/res.GooglePost"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "res.Post": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "instagram_url": {
                    "type": "string"
                },
                "wordpress_url": {
                    "type": "string"
                }
            }
        },
        "res.Posts": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "posts": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/res.Post"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "res.Token": {
            "type": "object",
            "properties": {
                "expired_at": {
                    "type": "string"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "res.WordpressInstagram": {
            "type": "object",
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "delete_hash": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "instagram_id": {
                    "type": "string"
                },
                "instagram_name": {
                    "type": "string"
                },
                "memo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "wordpress_domain": {
                    "type": "string"
                },
                "wordpress_site_title": {
                    "type": "string"
                }
            }
        },
        "res.WordpressInstagramDetail": {
            "type": "object",
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "delete_hash": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "instagram_id": {
                    "type": "string"
                },
                "instagram_name": {
                    "type": "string"
                },
                "memo": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "posts": {
                    "$ref": "#/definitions/res.Posts"
                },
                "start_date": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                },
                "wordpress_domain": {
                    "type": "string"
                },
                "wordpress_site_title": {
                    "type": "string"
                }
            }
        },
        "res.WordpressInstagramList": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "instagram_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/res.WordpressInstagram"
                    }
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
