// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/customers/{customer_id}": {
            "get": {
                "description": "指定された顧客IDの情報を取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customers"
                ],
                "summary": "顧客情報取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "顧客ID",
                        "name": "customer_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "顧客情報",
                        "schema": {}
                    },
                    "400": {
                        "description": "リクエストが不正です",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "顧客が見つかりません",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/instagram/sync/{customer_id}": {
            "post": {
                "description": "指定された顧客のInstagramアカウントを同期します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instagram"
                ],
                "summary": "Instagramアカウント同期",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "顧客ID",
                        "name": "customer_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "同期結果",
                        "schema": {}
                    },
                    "400": {
                        "description": "リクエストが不正です",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "顧客が見つかりません",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/instagram/{customer_id}": {
            "get": {
                "description": "指定された顧客のInstagramアカウント情報を取得します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instagram"
                ],
                "summary": "Instagramアカウント情報取得",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "顧客ID",
                        "name": "customer_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Instagramアカウント情報",
                        "schema": {}
                    },
                    "400": {
                        "description": "リクエストが不正です",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "顧客が見つかりません",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/sync": {
            "post": {
                "description": "全ての顧客のデータを同期します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sync"
                ],
                "summary": "全顧客データ同期",
                "responses": {
                    "200": {
                        "description": "全顧客同期完了",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/api/sync/{customer_id}": {
            "post": {
                "description": "指定された顧客IDのデータを同期します",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sync"
                ],
                "summary": "指定顧客データ同期",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "顧客ID",
                        "name": "customer_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "顧客同期完了",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "リクエストが不正です",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "顧客が見つかりません",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "内部サーバーエラー",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
